# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

require 'tasks/rails'


namespace :lfs do

  Rake::TestTask.new(:units_user => "db:test:prepare") do |t|
      t.libs << "test"
      t.pattern = 'test/unit/**/user_test.rb'
      t.verbose = true
  end
    
  Rake::TestTask.new(:functionals_sessions => "db:test:prepare") do |t|
    t.libs << "test"
    t.pattern = 'test/functional/**/sessions_controller_test.rb'
    t.verbose = true
  end    
  
  Rake::TestTask.new(:functionals_users => "db:test:prepare") do |t|
    t.libs << "test"
    t.pattern = 'test/functional/**/users_controller_test.rb'
    t.verbose = true
  end    
  
end  